version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: dev
    entrypoint: diesel migration run
    volumes:
      - .:/app

  app:
    build: .
    depends_on:
      - migrate
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_ENV: prod
    ports:
      - "8081:${PORT}"
    command: ["app"]
    volumes:
      - .:/app
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healtz"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
