[phases.setup]
nixPkgs = ['gcc', 'pkg-config', 'openssl.dev', 'postgresql.dev', 'glibc', 'stdenv.cc.cc.lib']

[phases.build]
cmds = ['cargo build --release']

[start]
cmd = './target/release/kharon-server'